name: ben_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^1.1.6
  cupertino_icons: ^0.1.2
  camera:
  path_provider:
  path: ^1.6.2
  crypto: ^2.1.1+1
  provider: ^3.1.0
  url_launcher: ^5.1.3
  flutter_html: ^0.11.0
  uuid: ^2.0.2
  mobx: ^0.3.8+1
  flutter_mobx: ^0.3.3+1
  flutter_masked_text: ^0.8.0
  fluttertoast: ^3.1.3
  convert: ^2.1.1
  encryptions: ^0.0.2

dev_dependencies:
  test: any
  mockito: ^4.1.1
  mobx_codegen: ^0.3.9+1
  build_runner:
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/banks/
    - assets/config/init.sql
  fonts:
    - family: ali
      fonts:
        - asset: assets/iconfont.ttf
    - family: fzltxh
      fonts:
        - asset: assets/fzltxh.ttf
flutter_intl:
  enabled: true