name: ben_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^1.1.6
  cupertino_icons: ^0.1.2
  path: ^1.6.2
  crypto: ^2.1.1+1
  provider: ^3.1.0
  url_launcher: ^5.1.3
  flutter_html: ^0.11.0
  msgpack2: ^2.0.0
  uuid: ^2.0.2
  encryptions:
    path: ./encryptions

dev_dependencies:
  test: any
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/banks/
    - assets/config/init.sql
  fonts:
    - family: ali
      fonts:
        - asset: assets/iconfont.ttf